//! `attend` CLI entry point.
//!
//! Argv parsing is handled by clap-derive (matches ADR-111's pattern for
//! the sibling `ways-cli` binary). The `Cli`/`Commands` definitions and
//! their doc comments live in `cli.rs` — that file is the canonical
//! source for runtime `--help` text AND for the markdown reference at
//! `docs/cli/attend.md` (generated by `bin/gen-docs.rs` via `clap-markdown`).
//!
//! Top-level shape:
//!   - Bare `attend` (no subcommand) prints the agent_fmt banner + help.
//!   - Every `attend X --help` is supplied automatically by clap.
//!   - The match in `main()` maps each enum variant to its `cmd::*::*`
//!     handler. Handlers take typed args directly.

mod cli;
mod cmd;
mod emit;
mod groups;
mod scenes;
mod sensors;
mod util;

/// Seen-set/state persistence now lives in the shared `attend-state`
/// crate (ADR-172): the drain verb, the sensor loop, and attend-chat's
/// purge consult all speak its wire format. The alias keeps every
/// existing `state::` call site unchanged.
use attend_state as state;

/// attend's settings, typed and loaded through their schema (ADR-503 §13).
use attend_config as config;

use clap::Parser;
use cli::{Cli, Commands, ConfigCmd, KeepwarmCmd, PermissionsCmd};
use sensors::Focus;

fn main() {
    // Bare invocation — print the agent_fmt banner + clap's auto-generated
    // help. Mirrors the ways-cli pattern (ADR-111). clap handles per-
    // subcommand `--help` automatically.
    let argv: Vec<String> = std::env::args().collect();
    let bare = argv.len() == 1;
    let top_help = argv.len() == 2 && (argv[1] == "help" || argv[1] == "--help" || argv[1] == "-h");

    if bare || top_help {
        print_banner();
        if bare {
            use clap::CommandFactory;
            let _ = Cli::command().print_help();
            println!();
            return;
        }
    }

    let cli = Cli::parse();
    let command = match cli.command {
        Some(c) => c,
        None => return,
    };

    match command {
        Commands::Run { catchup } => cmd::run::cmd_run_with_catchup(catchup),
        Commands::Peers => cmd::peers::cmd_peers(),
        Commands::Inbox { msg_id, limit, page, before, drain, format } => match (drain, msg_id) {
            (true, Some(_)) => {
                eprintln!("--drain drains everything pending; it cannot be combined with a message id");
                std::process::exit(2);
            }
            (true, None) => cmd::inbox::cmd_inbox_drain(&format),
            (false, Some(id)) => cmd::inbox::cmd_inbox_read(&id),
            (false, None) => cmd::inbox::cmd_inbox(limit, page, before),
        },
        Commands::Status => cmd::status::cmd_status(),
        Commands::Whoami { machine, display } => cmd::whoami::cmd_whoami(machine, display),
        Commands::Sensors => cmd::sensors::cmd_sensors(),
        Commands::Keepwarm { sub } => cmd::keepwarm::cmd_keepwarm(sub.unwrap_or(KeepwarmCmd::Status)),
        Commands::Send { to, channel, re, message } => {
            cmd::send::reject_flag_like("send", &message);
            cmd::send::cmd_send(to, channel, re, message);
        }
        Commands::Reply { to, channel, message } => {
            cmd::send::reject_flag_like("reply", &message);
            cmd::send::cmd_reply(to, channel, message);
        }
        Commands::Chat { passthrough } => exec_chat(passthrough),
        // Chat-idiom primary verbs (ADR-173). The `#` prefix is
        // tolerated so `attend join "#deploy"` works; bare names stay
        // primary because an unquoted `#` starts a shell comment.
        Commands::Join { name, pin } => cmd::channels::cmd_join(name.trim_start_matches('#'), pin),
        Commands::Leave { name } => cmd::channels::cmd_leave(name.trim_start_matches('#')),
        Commands::Channels { joined: true, sub: None } => cmd::channels::cmd_joined(),
        Commands::Channels { sub, .. } => match sub {
            None | Some(cli::ChannelsCmd::List) => cmd::channels::cmd_channels(),
            Some(cli::ChannelsCmd::Pin { name }) => cmd::channels::cmd_pin(&name),
            Some(cli::ChannelsCmd::Unpin { name }) => cmd::channels::cmd_unpin(&name),
            Some(cli::ChannelsCmd::Create { name, description }) => {
                cmd::channels::cmd_create(name.trim_start_matches('#'), &description.join(" "));
            }
            Some(cli::ChannelsCmd::Describe { name, description }) => {
                cmd::channels::cmd_describe(name.trim_start_matches('#'), &description.join(" "));
            }
        },
        Commands::Dissolve { name } => {
            cmd::channels::cmd_dissolve(name.trim_start_matches('#'));
        }
        Commands::Scene { name } => cmd::scene::cmd_scene(&name),
        Commands::Scenes => cmd::scene::cmd_scenes(),
        Commands::Tune { apply } => cmd::tune::cmd_tune(apply),
        Commands::Permissions { sub } => match sub.unwrap_or(PermissionsCmd::Audit) {
            PermissionsCmd::Audit => cmd::permissions::cmd_permissions_audit(),
        },
        Commands::Cleanup { dry_run, all } => {
            cmd::cleanup::cmd_cleanup(dry_run, all);
        }
        Commands::Config { sub } => dispatch_config(sub.unwrap_or(ConfigCmd::Show)),
    }
}

fn print_banner() {
    let version = format!("v{} ({})", env!("CARGO_PKG_VERSION"), env!("ATTEND_COMMIT"));
    agent_fmt::Banner::new("ATTEND")
        .subtitle("active awareness for Claude Code sessions")
        .version(&version)
        .gradient(&agent_fmt::GRADIENT_TEAL)
        .print();
}

fn exec_chat(passthrough: Vec<String>) -> ! {
    // `attend chat` is a thin shim that execs the standalone `attend-chat`
    // binary. Keeping the iocraft dependency (and its async runtime) out of
    // the attend crate means `attend status`, `attend send`, and the sensor
    // loop stay cheap to cold-start from hooks. See ADR-120.
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        let err = std::process::Command::new("attend-chat")
            .args(&passthrough)
            .exec();
        eprintln!("attend chat: failed to launch attend-chat: {}", err);
        eprintln!("  (is `attend-chat` on PATH? run `ways update` to install it)");
        std::process::exit(1);
    }
    #[cfg(not(unix))]
    {
        match std::process::Command::new("attend-chat")
            .args(&passthrough)
            .status()
        {
            Ok(status) => std::process::exit(status.code().unwrap_or(0)),
            Err(err) => {
                eprintln!("attend chat: failed to launch attend-chat: {}", err);
                eprintln!("  (is `attend-chat` on PATH? run `ways update` to install it)");
                std::process::exit(1);
            }
        }
    }
}

fn dispatch_config(sub: ConfigCmd) {
    match sub {
        ConfigCmd::Init => {
            let path = config::user_path();
            match config::init(&path) {
                Ok(true) => println!("wrote default config to {}", path.display()),
                Ok(false) => println!("{} exists; left as it is", path.display()),
                Err(e) => {
                    eprintln!("attend config init: {e}; nothing written");
                    std::process::exit(5);
                }
            }
        }
        ConfigCmd::Show => cmd::config_cmd::show(&Focus::default_focus().working_dir),
        ConfigCmd::Path => {
            println!("user:    {}", config::user_path().display());
            println!("project: {}", config::project_path(std::path::Path::new(&util::own_origin_cwd())).display());
        }
        ConfigCmd::Lint => {
            let code = cmd::config_cmd::lint(&util::own_origin_cwd());
            if code != 0 {
                std::process::exit(code);
            }
        }
    }
}
