def cmd_index(args):
    """Generate/update the ADR index from the active set (ADR-303)."""
    all_adrs = get_all_adrs(include_archived=True)
    adrs = [a for a in all_adrs if not is_archived(a.path)]
    archived = [a for a in all_adrs if is_archived(a.path)]
    domains = get_domains()
    legacy_range = get_legacy_range()

    # Sort by number
    def sort_key(adr):
        if not adr.number:
            return (9999, 0)
        parts = adr.number.split('.')
        return (int(parts[0]), int(parts[1]) if len(parts) > 1 else 0)

    adrs.sort(key=sort_key)
    archived.sort(key=sort_key)

    def status_cell(adr):
        note = supersession_note(adr)
        status = adr.status or '?'
        return f"{status} ({note})" if note else status

    project = get_config().get('project_name', 'this project')
    if repo_contract() == 'adr/v1':
        about = [
            f"This directory contains the Agent Decision Records (ADRs) for {project}, under the adr/v1 contract.",
            "A record's kind says what it holds: a decision, a spec kept current, or evidence (findings, surveys, explorations).",
            "",
            "## Record Format",
            "",
            "- **Kind:** decision / spec / evidence, as `adr.yaml` declares",
            "- **Status:** proposed / accepted / rejected / abandoned / superseded / archived",
            "- **Capability:** what the record is about, from the vocabulary in `adr.yaml`",
            "- **Decisions** also carry a verb (add / cut / change / retire / constrain), a basis, and open with a Summary",
            "- **Numbers** are permanent; a record's folder is its area",
        ]
    else:
        about = [
            f"This directory contains Agent Decision Records (ADRs) for {project}.",
            "Each ADR documents a significant architectural decision, its context, and consequences.",
            "",
            "## ADR Format",
            "",
            "All ADRs follow a consistent format:",
            "- **Status:** Draft / Proposed / Accepted / Deprecated / Superseded",
            "- **Date:** When the decision was made",
            "- **Deciders:** Who made the decision",
            "- **Context:** The problem or situation requiring a decision",
            "- **Decision:** The architectural choice made",
            "- **Consequences:** Benefits, drawbacks, and other impacts",
        ]
    lines = ["# Agent Decision Records", ""] + about + [
        "",
        f"_This index is auto-generated by `adr index`. Configuration: [`adr.yaml`](./adr.yaml)_",
        "",
    ]

    # By domain
    for domain, config in domains.items():
        domain_adrs = [a for a in adrs if a.domain == domain]
        if not domain_adrs:
            continue

        lines.append(f"## {config.get('name') or domain}")
        if config.get('description'):
            lines.append(f"_{config['description']}_")
        lines.append("")
        lines.append("| ADR | Title | Status |")
        lines.append("|-----|-------|--------|")

        for adr in domain_adrs:
            # Use actual folder from path, not config (supports multiple folders)
            folder = adr.path.parent.name
            filename = adr.path.name
            link = f"[ADR-{adr.number}](./{folder}/{filename})"
            lines.append(f"| {link} | {adr.title or '?'} | {status_cell(adr)} |")

        lines.append("")

    # Legacy (pre-domain numbering)
    legacy_label = get_config().get('legacy', {}).get('label', 'Legacy')
    uncategorized = [a for a in adrs if not a.domain]
    if uncategorized:
        lines.append(f"## {legacy_label}")
        lines.append("")
        lines.append("| ADR | Title | Status |")
        lines.append("|-----|-------|--------|")

        for adr in uncategorized:
            rel_path = adr.path.relative_to(adr.path.parent.parent)
            link = f"[ADR-{adr.number}](./{rel_path})"
            lines.append(f"| {link} | {adr.title or '?'} | {status_cell(adr)} |")

        lines.append("")

    # Archived ADRs: collapsed, not main-table rows (ADR-303)
    if archived:
        arch_root = get_project_root() / 'docs' / 'architecture'
        lines.append("## Archived")
        lines.append("")
        lines.append(f"<details><summary>{len(archived)} archived ADRs — "
                     "no longer part of the active set; kept for history</summary>")
        lines.append("")
        lines.append("| ADR | Title | Status |")
        lines.append("|-----|-------|--------|")
        for adr in archived:
            rel_path = adr.path.relative_to(arch_root)
            link = f"[ADR-{adr.number}](./{rel_path})"
            lines.append(f"| {link} | {adr.title or '?'} | {status_cell(adr)} |")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    content = '\n'.join(lines)

    # Check against existing index
    index_path = get_project_root() / 'docs' / 'architecture' / 'INDEX.md'

    if index_path.exists():
        existing = index_path.read_text()
        if existing == content:
            print(f"Index is up to date: {relative_path(index_path)}")
            print(f"  {len(adrs)} ADRs across {len(domains)} domains")
            return 0

        # Show what changed
        existing_lines = existing.splitlines()
        new_lines = content.splitlines()

        added = len([l for l in new_lines if l not in existing_lines])
        removed = len([l for l in existing_lines if l not in new_lines])

        print(f"Index needs updating: {relative_path(index_path)}")
        print(f"  {len(adrs)} ADRs across {len(domains)} domains")
        print(f"  Changes: +{added} -{removed} lines")

        if not args.yes:
            try:
                response = input("\nUpdate index? [y/N]: ")
                if response.lower() != 'y':
                    print("Skipped.")
                    return 0
            except (KeyboardInterrupt, EOFError):
                print("\nSkipped.")
                return 0

    index_path.write_text(content)
    print(f"Updated: {relative_path(index_path)}")
    return 0

