#!/usr/bin/env python3
"""
ADR - Architecture Decision Record CLI Tool

A librarian for managing Architecture Decision Records.

Usage:
    adr list [--domain DOMAIN] [--status STATUS] [--group] [--archived|--all]
    adr view <number>          # View an ADR (aliases: v, show)
    adr new <domain> <title>
    adr rename <number> [new-title] [--slug SLUG]
    adr archive <number> --reason "..." [--superseded-by ADR-N[,ADR-M]] [--status S] [--dry-run]
    adr lint [--check] [paths...]
    adr cite [--check] [paths...]
    adr accept <number> [--dry-run]
    adr reject|abandon <number> --reason "..." [--dry-run]
    adr import scan <paths...> [--force]
    adr import apply [sheets...] [--partial] [--force]
    adr index [-y]
    adr domains
    adr domain add <name> --range A-B --folder F [--label L] [--description D]
    adr domain rename <old> <new> [--folder F] [--dry-run]
    adr domain move <number> <domain> [--dry-run]
    adr domain move --plan <file.yaml> [--dry-run]
    adr config

Configuration is loaded from docs/architecture/adr.yaml
"""

# Generated by hooks/ways/documentation/adr/assemble from the modules in src/.
# In agent-ways, edit src/ and re-run assemble. A vendored copy is yours to
# customize (ADR-177).

import argparse
import hashlib
import os
import posixpath
import re
import subprocess
import sys
from datetime import date
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional

# Check for PyYAML
try:
    import yaml
except ImportError:
    print("Error: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    print("       Or system-wide: sudo apt install python3-yaml", file=sys.stderr)
    sys.exit(1)

# Vendored-tool version (ADR-177). Bump when this tool changes — way macros
# compare it against the installed template to tell stale from customized.
TOOL_VERSION = "2.0.0"

# Statuses that mean "no longer in force" — used by archive and the
# partial-supersession convention (ADR-303 / issue #438 option C2).
NON_ACTIVE_STATUSES = {'Superseded', 'Deprecated', 'Rejected'}
# adr/v1's record lifecycle is lowercase and adds abandoned and archived
# (ADR-304 §2). The v0 set above stays exact, so v0 repos see no change.
V1_NON_ACTIVE_STATUSES = {'superseded', 'deprecated', 'rejected', 'abandoned', 'archived'}

def is_non_active(status) -> bool:
    if not status:
        return False
    if repo_contract() == 'adr/v1':
        return str(status).lower() in V1_NON_ACTIVE_STATUSES
    return status in NON_ACTIVE_STATUSES

