#!/usr/bin/env python3
"""
ADR - Architecture Decision Record CLI Tool

A librarian for managing Architecture Decision Records.

Usage:
    adr list [--domain DOMAIN] [--status STATUS] [--group] [--archived|--all]
    adr view <number>          # View an ADR (aliases: v, show)
    adr new <domain> <title>
    adr rename <number> [new-title] [--slug SLUG]
    adr archive <number> --reason "..." [--superseded-by ADR-N[,ADR-M]] [--status S] [--dry-run]
    adr lint [--check] [paths...]
    adr index [-y]
    adr domains
    adr config

Configuration is loaded from docs/architecture/adr.yaml
"""

# Generated by hooks/ways/documentation/adr/assemble from the modules in src/.
# In agent-ways, edit src/ and re-run assemble. A vendored copy is yours to
# customize (ADR-177).

import argparse
import re
import subprocess
import sys
from datetime import date
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional

# Check for PyYAML
try:
    import yaml
except ImportError:
    print("Error: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    print("       Or system-wide: sudo apt install python3-yaml", file=sys.stderr)
    sys.exit(1)

# Vendored-tool version (ADR-177). Bump when this tool changes — way macros
# compare it against the installed template to tell stale from customized.
TOOL_VERSION = "1.2.0"

# Statuses that mean "no longer in force" — used by archive and the
# partial-supersession convention (ADR-303 / issue #438 option C2).
NON_ACTIVE_STATUSES = {'Superseded', 'Deprecated', 'Rejected', 'Abandoned', 'Archived'}

def is_non_active(status) -> bool:
    """Case-insensitive: v0 statuses are capitalized, adr/v1's are lowercase
    (ADR-304 §2), and Abandoned and Archived exist only in v1."""
    return bool(status) and str(status).capitalize() in NON_ACTIVE_STATUSES

